# The numpy.random package

***

This notebook will discuss the numpy.random package in Python.

It will focus on:
* Explaining the overall use of the package.
* Explaining the use of "Simple random data" and "Permutations" functions.
* Explaining the use and purpose of 5 "Distributions" functions.
* Explaining the use of seeds in generating pseudorandom numbers.

***

## NumPy
***

"![NumPy](https://img.shields.io/badge/numpy-%23013243.svg?style=for-the-badge&logo=numpy&logoColor=white) (also known as Numerical Python) is used in almost field of science and engineering. It's the universal standard for working with numerical data in Python. The NumPy API is also used extensively in other packages such as:
![Pandas](https://img.shields.io/badge/pandas-%23150458.svg?style=for-the-badge&logo=pandas&logoColor=white) 
![SciPy](https://img.shields.io/badge/SciPy-%230C55A5.svg?style=for-the-badge&logo=scipy&logoColor=%white) 
![scikit-learn](https://img.shields.io/badge/scikit--learn-%23F7931E.svg?style=for-the-badge&logo=scikit-learn&logoColor=white) 
Matplotlib 
& others.

The NumPy library contains multidimensional array and matrix data structures. It provides ndarray, a homogeneous n-dimensional array object, with methods to efficiently operate on it. NumPy can be used to perform a wide variety of mathematical operations on arrays." [<sup>1</sup>]( https://numpy.org/doc/stable/user/absolute_beginners.html#welcome-to-numpy)


#### Okay, but what's an array?

"An array is a central data structure of the NumPy library. An array is a grid of values and it contains information about the raw data, how to locate an element, and how to interpret an element. It has a grid of elements that can be indexed in various ways. The elements are all of the same type, referred to as the array dtype." [<sup>2</sup>](https://numpy.org/doc/stable/user/absolute_beginners.html#what-is-an-array)

"You might occasionally hear an array referred to as a “ndarray,” which is shorthand for “N-dimensional array.” An N-dimensional array is simply an array with any number of dimensions. You might also hear 1-D, or one-dimensional array, 2-D, or two-dimensional array, and so on." [<sup>3</sup>](https://numpy.org/doc/stable/user/absolute_beginners.html#more-information-about-arrays)

#### How do you create arrays?

"There are several ways to create arrays.

For example, you can create an array from a regular Python list or tuple using the array function. The type of the resulting array is deduced from the type of the elements in the sequences." [<sup>4</sup>](https://numpy.org/doc/stable/user/quickstart.html#array-creation)

"To create a NumPy array, you can use the function *np.array()*.

All you need to do to create a simple array is pass a list to it. If you choose to, you can also specify the type of data in your list." [<sup>5</sup>](https://numpy.org/doc/stable/user/absolute_beginners.html#how-to-create-a-basic-array)

#### What do arrays look like?

Okay, so now that we know how to create an array, let's have a look at what they actually look like.

A basic array looks something like this[<sup>5</sup>](https://numpy.org/doc/stable/user/absolute_beginners.html#how-to-create-a-basic-array):

In [3]:
# First of all, you need to import the Numpy library into Python
import numpy as np
# Using the np.array function, you add a regular Python list in square brackets and save it as 'a'
a = np.array([2, 3, 4])
print (a)
# Print out the list you've saved as 'a'

[2 3 4]


What about the multi-dimensional arrays mentioned earlier, what do they look like?

"NumPy arrays can be defined using Python sequences such as lists and tuples. Lists and tuples are defined using [...] and (...), respectively. Lists and tuples can define ndarray creation:

* a list of numbers will create a 1D array,
* a list of lists will create a 2D array,
* further nested lists will create higher-dimensional arrays. In general, any array object is called an ndarray in NumPy." [<sup>6</sup>](https://numpy.org/doc/stable/user/basics.creation.html#converting-python-sequences-to-numpy-arrays)

"One-dimensional arrays are then printed as rows, bidimensionals as matrices and tridimensionals as lists of matrices." [<sup>7</sup>](https://numpy.org/doc/stable/user/quickstart.html#printing-arrays)

In [9]:
a1D = np.array([1, 2, 3, 4])
print (a1D)
a2D = np.array([[1, 2], [3, 4]])
print (a2D)
a3D = np.array([[[1, 2], [3, 4]],[[5, 6], [7, 8]]])
print (a3D)

[1 2 3 4]
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### Okay, so why not use Python lists instead?

"NumPy arrays are faster and more compact than Python lists. An array consumes less memory and is convenient to use. NumPy uses much less memory to store data and it provides a mechanism of specifying the data types. This allows the code to be optimized even further." [<sup>8</sup>](https://numpy.org/doc/stable/user/absolute_beginners.html#whats-the-difference-between-a-python-list-and-a-numpy-array)
***

## numpy.random

Now that we have an understanding of what NumPy is used for, let's have a look at the numpy.random package and what it's used for.

"Numpy’s random number routines produce pseudo random numbers using combinations of a BitGenerator to create sequences and a Generator to use those sequences to sample from different statistical distributions:

BitGenerators: Objects that generate random numbers. These are typically unsigned integer words filled with sequences of either 32 or 64 random bits.

Generators: Objects that transform sequences of random bits from a BitGenerator into sequences of numbers that follow a specific probability distribution (such as uniform, Normal or Binomial) within a specified interval.

"Since Numpy version 1.17.0 the Generator can be initialized with a number of different BitGenerators. It exposes many different probability distributions." [<sup>9</sup>](https://numpy.org/doc/stable/reference/random/index.html?highlight=numpy%20random#random-sampling-numpy-random)

First of all, what is a pseudo random number?

In order to explain this, we will need to have a deeper understanding of "random" in computing.

This is explained very eloquently on W3Schools:

"Random number does NOT mean a different number every time. Random means something that can not be predicted logically. Computers work on programs, and programs are definitive sets of instructions. [Therefore]... it means there must be some algorithm to generate a random number as well. If there is a program to generate random number[s] it can be predicted, this it is not truly random. Random numbers generated through a generation algorithm are called pseudo random." [<sup>10</sup>](https://www.w3schools.com/python/numpy/numpy_random.asp)

Now that we have an understanding of what a pseudo random number is, what are the Bit Generator and Generator that we have to use in order to produce them, as the documentation says?

# Functions in numpy.random

***

## Simple random data

URL: https://numpy.org/doc/stable/reference/random/legacy.html#simple-random-data

***

**random.Generator.integers(low, high=None, size=None, dtype=np.int64, endpoint=False)**

URL: https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.integers.html#numpy.random.Generator.integers

Return random numbers that are inclusive of the number you put into the low argument and exclusive of the number you put into the high argument (if you use a number there). If you don't pass a number into the high field, the results will be from 0 up to but not including the number you passed into the low argument.

The size refers to the shape of the array that is returned. If none is specified, only one number will be returned.

The dtype refers to A data type object (an instance of numpy.dtype class) describes how the bytes in the fixed-size block of memory corresponding to an array item should be interpreted. https://numpy.org/doc/stable/reference/arrays.dtypes.html#data-type-objects-dtype

The endpointbool refers to the option to exclude the endpoint if you wish. It defaults as false unless you choose to set it. https://numpy.org/doc/stable/reference/generated/numpy.linspace.html#numpy.linspace 

Returns:
One number - if no size is specified 
or
An ndarray of random numbers from a distribution.

The code will look something like this: random.Generator.integers(low, high=None, size=None, dtype=np.int64, endpoint=False)

Here is an example of the code: XYZ
***
URL:
https://numpy.org/doc/stable/reference/random/generator.html#simple-random-data

***

* random

URL: https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.random.html#numpy.random.Generator.random

Return random floats in the half-open interval [0.0, 1.0).

Results are from the “continuous uniform” distribution over the stated interval. To sample multiply the output of random by (b-a) and add a:

(b - a) * random() + a Parameters sizeint or tuple of ints, optional Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. Default is None, in which case a single value is returned.

dtypedtype, optional Desired dtype of the result, only float64 and float32 are supported. Byteorder must be native. The default value is np.float64.

outndarray, optional Alternative output array in which to place the result. If size is not None, it must have the same shape as the provided size and must match the type of the output values.

Returns outfloat or ndarray of floats Array of random floats of shape size (unless size=None, in which case a single float is returned).

* choice

URL: https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.choice.html#numpy.random.Generator.choice

random.Generator.choice(a, size=None, replace=True, p=None, axis=0, shuffle=True)
Generates a random sample from a given array

Parameters
a{array_like, int}
If it's an ndarray, the sample must be generated from the array. 

If it's an integer, the random sample is generated from 

If an ndarray, a random sample is generated from its elements. If an int, the random sample is generated from np.arange(a).

size{int, tuple[int]}, optional
Output shape. 

If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn from the 1-d a. 

* If a has more than one dimension, the size shape will be inserted into the axis dimension, so the output ndim will be a.ndim - 1 + len(size). 

Default is None, in which case a single value is returned.

replacebool, optional
Whether the sample is with or without replacement. Default is True, meaning that a value of a can be selected multiple times.

p1-D array_like, optional
The probabilities associated with each entry in a. If not given, the sample assumes a uniform distribution over all entries in a.

axisint, optional
The axis along which the selection is performed. The default, 0, selects by row.

shufflebool, optional
Whether the sample is shuffled when sampling without replacement. Default is True, False provides a speedup.

Returns
samplessingle item or ndarray
The generated random samples

Raises
ValueError
If a is an int and less than zero, if p is not 1-dimensional, if a is array-like with a size 0, if p is not a vector of probabilities, if a and p have different lengths, or if replace=False and the sample size is greater than the population size.

* bytes

URL: https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.bytes.html#numpy.random.Generator.bytes

random.Generator.bytes(length)
Return random bytes.

Parameters
lengthint
Number of random bytes.

Returns
outbytes
String of length length.


## Permutations

URL: https://numpy.org/doc/stable/reference/random/generated/numpy.random.permutation.html

https://numpy.org/doc/stable/reference/random/index.html#random-quick-start

https://www.w3schools.com/python/numpy/numpy_random_permutation.asp

***

New:
* shuffle

URL: https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.shuffle.html#numpy.random.Generator.shuffle

random.Generator.shuffle(x, axis=0)
Modify an array or sequence in-place by shuffling its contents.

The order of sub-arrays is changed but their contents remains the same.

Parameters
xndarray or MutableSequence
The array, list or mutable sequence to be shuffled.

axisint, optional
The axis which x is shuffled along. Default is 0. It is only supported on ndarray objects.

Returns
None

* permutation

URL: https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.permutation.html#numpy.random.Generator.permutation

random.Generator.permutation(x, axis=0)
Randomly permute a sequence, or return a permuted range.

Parameters
xint or array_like
If x is an integer, randomly permute np.arange(x). If x is an array, make a copy and shuffle the elements randomly.

axisint, optional
The axis which x is shuffled along. Default is 0.

Returns
outndarray
Permuted sequence or array range.

* permuted

URL: https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.permuted.html#numpy.random.Generator.permuted

random.Generator.permuted(x, axis=None, out=None)
Randomly permute x along axis axis.

Unlike shuffle, each slice along the given axis is shuffled independently of the others.

Parameters
xarray_like, at least one-dimensional
Array to be shuffled.

axisint, optional
Slices of x in this axis are shuffled. Each slice is shuffled independently of the others. If axis is None, the flattened array is shuffled.

outndarray, optional
If given, this is the destinaton of the shuffled array. If out is None, a shuffled copy of the array is returned.

Returns
ndarray
If out is None, a shuffled copy of x is returned. Otherwise, the shuffled array is stored in out, and out is returned

***
URL: https://numpy.org/doc/stable/reference/random/generator.html#permutations

***

The permutation function is used to "randomly permute a sequence, or return a permuted range. If [it] is a multi-dimensional array, it is only shuffled along its first index." []. 

Legacy:

In [1]:
# code from doc goes here

New:

In [21]:
from numpy.random import default_rng
rng = default_rng()
values = ([1,2,3,4,5,6,7,8,9,10])
print (rng.permutation(values))

[ 2  3  8 10  5  9  7  1  6  4]


***

## Distributions

***

There are many functions available in numpy which can be used to visualise your data. This notebook is going to look at 5 of them in-depth.

New:

URL: https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.uniform.html#numpy.random.Generator.uniform
***
URL:
https://numpy.org/doc/stable/reference/random/generator.html#distributions

***

# Seeds in numpy.random

***

Legacy: 
* get_state
* set_state
* seed

URL: https://numpy.org/doc/stable/reference/random/legacy.html#seeding-and-state

New:

https://numpy.org/doc/stable/reference/random/legacy.html#numpy.random.RandomState

https://numpy.org/doc/stable/reference/random/generator.html#numpy.random.Generator

URL: 
https://numpy.org/doc/stable/reference/random/generator.html#random-generator

# References

***

[1] https://numpy.org/doc/stable/user/absolute_beginners.html#welcome-to-numpy

[2] https://numpy.org/doc/stable/user/absolute_beginners.html#what-is-an-array

[3] https://numpy.org/doc/stable/user/absolute_beginners.html#more-information-about-arrays

[4] https://numpy.org/doc/stable/user/quickstart.html#array-creation

[5] https://numpy.org/doc/stable/user/absolute_beginners.html#how-to-create-a-basic-array

[6] https://numpy.org/doc/stable/user/basics.creation.html#converting-python-sequences-to-numpy-arrays

[7] https://numpy.org/doc/stable/user/quickstart.html#printing-arrays

[8] https://numpy.org/doc/stable/user/absolute_beginners.html#whats-the-difference-between-a-python-list-and-a-numpy-array

[9] https://numpy.org/doc/stable/reference/random/index.html?highlight=numpy%20random#random-sampling-numpy-random

[10] https://www.w3schools.com/python/numpy/numpy_random.asp

https://numpy.org/doc/stable/reference/random/index.html

https://github.com/Ileriayo/markdown-badges

### End